In [6]:
import numpy as np
import pandas as panda
import matplotlib as matplot

print "hello"


hello


In [7]:
x = 3
print 3

3


In [8]:
animals =['cat','dog','ssdf']

for idx,animal in enumerate(animals):
    print '%d:%s' % (idx+1,animal)

1:cat
2:dog
3:ssdf


Working with matplot , numpy , pandas 

In [9]:
import numpy as np
import pandas as pandas
import matplotlib.pyplot as pit

my_list = [1,2,3]

np.array(my_list)


array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[5,5,5]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 5, 5]])

In [11]:
np.arange(50,100,7)

array([50, 57, 64, 71, 78, 85, 92, 99])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
np.linspace(0,3)

array([ 0.        ,  0.06122449,  0.12244898,  0.18367347,  0.24489796,
        0.30612245,  0.36734694,  0.42857143,  0.48979592,  0.55102041,
        0.6122449 ,  0.67346939,  0.73469388,  0.79591837,  0.85714286,
        0.91836735,  0.97959184,  1.04081633,  1.10204082,  1.16326531,
        1.2244898 ,  1.28571429,  1.34693878,  1.40816327,  1.46938776,
        1.53061224,  1.59183673,  1.65306122,  1.71428571,  1.7755102 ,
        1.83673469,  1.89795918,  1.95918367,  2.02040816,  2.08163265,
        2.14285714,  2.20408163,  2.26530612,  2.32653061,  2.3877551 ,
        2.44897959,  2.51020408,  2.57142857,  2.63265306,  2.69387755,
        2.75510204,  2.81632653,  2.87755102,  2.93877551,  3.        ])


np.eye(4)

Generaetes identical matrix np eye()

In [15]:
np.random.rand(1,10)

array([[ 0.3504852 ,  0.41426929,  0.85755857,  0.35057361,  0.52665862,
         0.38988235,  0.64849307,  0.52953789,  0.63037552,  0.17934989]])

In [16]:
np.random.randint(1,10)

4

Reshaping

In [17]:
arr = np.arange(30)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [19]:
arr.max()

29

In [20]:
arr.argmax() #returns index of max values

29

In [21]:
arr.shape

(30,)

In [22]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [23]:
arr.reshape(30,1).shape

(30, 1)

In [24]:
random_array = np.arange(5,20)
random_array


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
random_array[2]

7

In [26]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# # 2D Arrays

In [27]:
arr_2d = np.array(([5,0,1],[6,6,7],[8,7,9]))
arr_2d


array([[5, 0, 1],
       [6, 6, 7],
       [8, 7, 9]])

In [28]:
arr_2d[:2]

array([[5, 0, 1],
       [6, 6, 7]])

In [29]:
arr_2d[:2,2:]

array([[1],
       [7]])

In [31]:
arr_2d = np.array(([5,0,1],[6,6,7],[8,7,9]))

arr_2d.shape(1)

TypeError: 'tuple' object is not callable

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr <4

array([ True,  True,  True, False, False, False, False, False, False, False], dtype=bool)

In [38]:
arr1 = np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
arr + arr1

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])